name: Announce a release

on:
  push:
    tags: announce-\d+.\d+.\d+

jobs:
  announce-a-release:
    name: Announce a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Announce
        uses: dashdash/release-action@1.2.0
        with:
          step: announce-a-release
          git_user_name: "Release Bot"
          git_user_email: "pedrotavares.dev@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
