name: Start a release

on:
  push:
    tags: release-\d+.\d+.\d+

jobs:
  start-a-release:
    name: Start a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Start
        uses: dashdash/release-action@1.2.9
        with:
          step: start-a-release
          git_user_name: "Release Bot"
          git_user_email: "pedrotavares.dev@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Announce
        uses: dashdash/release-action@1.2.9
        with:
          step: announce-a-release
          git_user_name: "Release Bot"
          git_user_email: "pedrotavares.dev@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
